[package]
name = "debcargo"
version = "2.3.0-alpha.0"
authors = [
 "Josh Triplett <josh@joshtriplett.org>",
 "Ximin Luo <infinity0@debian.org>",
 "Vasudev Kamath <vasudev@copyninja.info>"]
license = "MIT/Apache-2.0"
repository = "https://salsa.debian.org/rust-team/debcargo"
description = "Create a Debian package from a Cargo crate."

[dependencies]
cargo = "0.34"
clap = "2.18"
chrono = "0.4"
failure = "0.1"
filetime = "0.2"
flate2 = "1"
glob = "0.3"
itertools = "0.8"
regex = "1.0"
semver = "0.9"
semver-parser = "0.9"
tar = "0.4"
tempfile = "3"
walkdir = "2"
ansi_term = "0.11"
serde = "1.0"
serde_derive = "1.0"
textwrap = "0.11"
toml = "0.5"
git2 = "0.8"
